services:
  postgres:
    image: postgres:16
    container_name: quandoc-postgres
    environment:
      POSTGRES_DB: astrodoc
      POSTGRES_USER: astrodoc
      POSTGRES_PASSWORD: astrodoc_password
    ports:
      - '5455:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U astrodoc']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
